#数据库相关连接
spring:
  #  配置热部署,idea设置要求：
  #  ①修改IDEA设置，启用自动构建。在IDEA的设置中，找到“Build, Execution, Deployment” -> “Compiler”，然后勾选“Build project automatically”。
  #  ②修改IDEA的Advanced Settings。在IDEA的设置中，找到“Advanced Settings”，然后调整与热部署相关的设置，例如堆内存大小等。具体设置可能因IDEA版本和个人需求而有所不同。
  #  ③重新启动IDEA。完成以上步骤后，重新启动IDEA以使设置生效。
  spring:
    devtools:
      restart:
        enabled: true
  #  配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.51.221:3333/nulldemo?serverTimezone=Asia/Shanghai
    username: root
    password: 123wjyWJY...
    type: com.alibaba.druid.pool.DruidDataSource

    # 数据源其它配置
    initialSize: 5 #初始化连接数量
    minIdle: 5     #最小连接数
    maxActive: 1000  #最大连接数 2023/3/20修改最大连接数为1000
    maxWait: 60000 #获取连接最大等待时间
    #间隔多久进行一次检测 单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #是否缓存preparedStatement即PSCache 官网建议mysql下关闭，个人建议如果想用sql防火墙建议开启
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #允许Bean或依赖循环引用
  main:
    allow-circular-references: true

# 指定MyBatis配置文件及映射文件位置
mybatis:
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.szpx.entity
  #如果不存在，注释掉,要求Mapper.java和Mapper.xml需要在同一目录下
  mapper-locations: classpath:*Mapper.xml

  #关闭Thymeleaf的缓存
thymeleaf:
  cache: false
#配置项目访问端口为8086
server:
  port: 8086

